### ISSUE TITLE
Provide access to correlation information in the response body expression

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#1578]
What should we do?

We should provide the result of successful correlations via the webhook response body expression by making it available in the expression context. We will re-use the existing correlation variable to expose this functionality.

Why should we do it?

Customers are requesting access to it: https://jira.camunda.com/browse/SUPPORT-19621
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/connectors/pull/1584
- [x] Backport PR to 8.3: https://github.com/camunda/connectors/pull/1584#issuecomment-1855843749
- [x] Document the correlation object in the docs for the Webhook Connector: https://github.com/camunda/camunda-docs/pull/3098
```

**Comment by buss-dev** [comment]
I asked you in the forum about this. I tested the correlation in the response body expression in version 8.3.3, and it returned messageKey and tenantId. However, I have a doubt: Is there a way to return the processInstanceKey with this object?

**Comment by sbuettner** [comment]
Hi @buss-dev, yes. But this only works for Connectors that internally create process instances via the https://docs.camunda.io/docs/apis-tools/grpc/#createprocessinstance-rpc API and this is only the case for Connectors base on `bpmn:StartEvent` that dont publish a message. My assumption is that you tried to use it via a  `Message Start Event` based Connector. Just try to use the `Webhook Start Event Connector` for example.

**Comment by buss-dev** [comment]
And about the warning: "Inbound Connector start events are on a deprecation path. Please use Inbound Connector message start events instead." in the documentation?

**Comment by sbuettner** [comment]
@buss-dev Thanks for your response. We will remove this note when updating the docs.

**Comment by buss-dev** [comment]
Thanks for your help!
