### ISSUE TITLE
[Master issue] Manage and Run

### ISSUE THREAD

**Issue by johnBgood** [camunda/connectors#3766]
__What should we do?__

## Product hub issue
This Master issue will track the progress of the [Manage and Run epic](https://github.com/camunda/product-hub/issues/1063).

## Design document
You can find the HFW designs [here](https://www.figma.com/design/6HqejaS9878YYWCLLqRsUI/Manage-Inbound-Connectors?node-id=92-39126&node-type=section&t=hntNBg8dCAqCjVxn-0).

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/connectors/issues/3767
- [ ] https://github.com/camunda/connectors/issues/3771
- [ ] https://github.com/camunda/connectors/issues/3881
- [ ] https://github.com/camunda/connectors/issues/3879
- [ ] https://github.com/camunda/connectors/issues/3885
- [ ] https://github.com/camunda/connectors/issues/3990
```
